### ISSUE TITLE
Lexer detection

### ISSUE THREAD

**Issue by rgieseke** [girvo/hack-textadept#1]
Hi,

great to see a new lexer for Textadept!

The extension setting should go into `~/.textadept/init.lua` I think, `properties.lua` is loaded for every new buffer and view to set custom style attributes etc.

```
textadept.file_types.extensions.hh = "hack"
```

I don't know much about HHVM, but it should be wrapping PHP, right? If yes, one could suggest adding

```
textadept.file_types.extensions.php = "hack"
```

as well …

**Comment by girvo** [comment]
Thanks @rgieseke! I'll definitely clean that up :) 

Funnily, Hack isn't ever embedded in HTML (or PHP, despite the powerful interop) -- so there's a lot of cleaning up I can do with it. 

Do you know if it's possible to call out to an external program on save for a particular lexer? I'd love to integrate the type-checker into Textadept for Hack (very easy to do, as the type-checker has machine readable output specifically for this), for when I move this into a proper plugin :)

**Comment by rgieseke** [comment]
> Funnily, Hack isn't ever embedded in HTML (or PHP, despite the powerful interop) -- so there's a lot of cleaning up I can do with it.

Ah, hadn't thought about that! :-)

On-save events are supported, for example: 
- Lua: http://foicica.com/hg/textadept/file/4e01454e1f89/modules/lua/init.lua#l121
- CoffeeScript: https://github.com/rgieseke/ta-coffeescript/blob/master/init.lua#L41

**Comment by girvo** [comment]
> On-save events are supported, for example: 

Oh awesome, cheers @rgieseke -- the CoffeeScript one looks like it's a perfect template for what I had in mind!
